version: '3.8'

services:
  backend:
    image: ghcr.io/fruitcake514/emulatorjsPWA/backend:latest  # Pull from GitHub Container Registry (GHCR)
    environment:
      - PORT=4000
      - DB_PATH=/app/database.sqlite
      - SECRET_KEY=your_secret_key
    volumes:
      - backend_data:/app  # Store database persistently
    networks:
      - app_network
    restart: always

  frontend:
    image: ghcr.io/fruitcake514/emulatorjsPWA/frontend:latest  # Pull from GHCR
    environment:
      - REACT_APP_API_URL=http://backend:4000
    volumes:
      - frontend_data:/app/public  # Persist frontend assets (optional)
    depends_on:
      - backend
    networks:
      - app_network

  emulator:
    image: ghcr.io/fruitcake514/emulatorjsPWA/emulator:latest  # Pull from GHCR
    environment:
      - PORT=5000
    volumes:
      - emulator_data:/app/emulator_files  # Persist emulator files
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  backend_data:  # Stores SQLite database persistently
  frontend_data:  # Stores frontend settings, assets, etc.
  emulator_data:  # Stores emulator configurations and ROMs
