version: '3.8'

services:
  backend:
    build: .
    environment:
      - PORT=4000
      - DB_PATH=/app/database.sqlite
      - SECRET_KEY=your_secret_key
    volumes:
      - ./backend/database.sqlite:/app/database.sqlite
    networks:
      - app_network
    restart: always

  frontend:
    build: .
    environment:
      - REACT_APP_API_URL=http://backend:4000
    depends_on:
      - backend
    networks:
      - app_network

  emulator:
    build: .
    environment:
      - PORT=5000
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
